require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - 'db/{schema.rb}'
    - 'db/migrate/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{bundle,rails,rake,setup,spring,update,yarn}'
    - 'config.ru'
    - 'Rakefile'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
